### ISSUE TITLE
erro 500 tentando criar caixa de entrada na integração da evolution com chatwoot

### ISSUE THREAD

**Issue by mordocks** [cwmkt/easypanelevotypebot#1]
depois de realizar todos os passos, quando vou fazer a integração da evolution com o chatwoot estou recebendo esse erro: 
{ "status": 500, "error": "Internal Server Error", "response": { "message": "connect ECONNREFUSED meuIP:443" } }

**Comment by GustavoFz** [comment]
Conseguiu resolver? Estou com o mesmo problema.

**Comment by mh1710** [comment]
Tente mudar a senha do seu mongo em credentials do mongo
Copie a Internal Connection URL
Vá em evolution -> Enviroment 
E cole em DATABASE_CONNECTION_URI= mantendo o @chatwoot_mongo:27017

Tive o mesmo erro aqui e consegui solucionar fazendo isso
